/*
Copyright 2021 The Rama Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	networkingv1 "github.com/oecp/rama/pkg/apis/networking/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRemoteVteps implements RemoteVtepInterface
type FakeRemoteVteps struct {
	Fake *FakeNetworkingV1
}

var remotevtepsResource = schema.GroupVersionResource{Group: "networking.alibaba.com", Version: "v1", Resource: "remotevteps"}

var remotevtepsKind = schema.GroupVersionKind{Group: "networking.alibaba.com", Version: "v1", Kind: "RemoteVtep"}

// Get takes name of the remoteVtep, and returns the corresponding remoteVtep object, and an error if there is any.
func (c *FakeRemoteVteps) Get(ctx context.Context, name string, options v1.GetOptions) (result *networkingv1.RemoteVtep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(remotevtepsResource, name), &networkingv1.RemoteVtep{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkingv1.RemoteVtep), err
}

// List takes label and field selectors, and returns the list of RemoteVteps that match those selectors.
func (c *FakeRemoteVteps) List(ctx context.Context, opts v1.ListOptions) (result *networkingv1.RemoteVtepList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(remotevtepsResource, remotevtepsKind, opts), &networkingv1.RemoteVtepList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &networkingv1.RemoteVtepList{ListMeta: obj.(*networkingv1.RemoteVtepList).ListMeta}
	for _, item := range obj.(*networkingv1.RemoteVtepList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested remoteVteps.
func (c *FakeRemoteVteps) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(remotevtepsResource, opts))
}

// Create takes the representation of a remoteVtep and creates it.  Returns the server's representation of the remoteVtep, and an error, if there is any.
func (c *FakeRemoteVteps) Create(ctx context.Context, remoteVtep *networkingv1.RemoteVtep, opts v1.CreateOptions) (result *networkingv1.RemoteVtep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(remotevtepsResource, remoteVtep), &networkingv1.RemoteVtep{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkingv1.RemoteVtep), err
}

// Update takes the representation of a remoteVtep and updates it. Returns the server's representation of the remoteVtep, and an error, if there is any.
func (c *FakeRemoteVteps) Update(ctx context.Context, remoteVtep *networkingv1.RemoteVtep, opts v1.UpdateOptions) (result *networkingv1.RemoteVtep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(remotevtepsResource, remoteVtep), &networkingv1.RemoteVtep{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkingv1.RemoteVtep), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRemoteVteps) UpdateStatus(ctx context.Context, remoteVtep *networkingv1.RemoteVtep, opts v1.UpdateOptions) (*networkingv1.RemoteVtep, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(remotevtepsResource, "status", remoteVtep), &networkingv1.RemoteVtep{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkingv1.RemoteVtep), err
}

// Delete takes name of the remoteVtep and deletes it. Returns an error if one occurs.
func (c *FakeRemoteVteps) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(remotevtepsResource, name), &networkingv1.RemoteVtep{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRemoteVteps) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(remotevtepsResource, listOpts)

	_, err := c.Fake.Invokes(action, &networkingv1.RemoteVtepList{})
	return err
}

// Patch applies the patch and returns the patched remoteVtep.
func (c *FakeRemoteVteps) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkingv1.RemoteVtep, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(remotevtepsResource, name, pt, data, subresources...), &networkingv1.RemoteVtep{})
	if obj == nil {
		return nil, err
	}
	return obj.(*networkingv1.RemoteVtep), err
}
